### ISSUE TITLE
Data seeder error

### ISSUE THREAD

**Issue by darron1217** [avored/install#1]
@indpurvesh 
`Parse error: syntax error, unexpected '=', expecting ']'`

![image](https://user-images.githubusercontent.com/8064923/33662941-3f6e729a-dad1-11e7-92c3-bd6e78db80d3.png)

**Comment by darron1217** [comment]
I got another error
`html_entity_decode() expects at least 1 parameter, 0 given`

**Comment by indpurvesh** [comment]
i am working on this bug

**Comment by indpurvesh** [comment]
It should be fixed.
